services:
  postgres:
    image: postgres:16
    container_name: myapi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_checkin:/var/lib/postgresql/data

volumes:
  pgdata_checkin:
